---
pool:
  name: Azure Pipelines  
  vmImage: ubuntu-22.04

trigger:
  - master


steps: 
  - task: DotNetCoreCLI@2
    displayName: build the code
    inputs:
      command: build
      projects: src/NopCommerce.sln
      configuration: Release



  