trigger:
  - master
    
pool: default

steps:
  - task: DotNetCoreCLI@2
    displayName: Build&package
    inputs:
      command: 'build'
      projects: src/ NopCommerce.sln
      publishTestResults: true

