trigger:
  - master
    
pool: default

steps:
  - task: DotNetCoreCLI@2
    displayName: Build&package
    inputs:
      command: 'build'
      inputs:  
      packageType: 'sdk'  
      version: '7.0' 
      projects: src/ NopCommerce.sln
      publishTestResults: true

