---
pool: 
  name: Azure Pipelines
  vmImage: ubuntu-22.04

trigger:
  - master
jobs:
  - job: dotnetbuild
    steps:
      - bash: "echo staging directory $(Build.ArtifactStagingDirectory) and number $(Build.BuildNumber)"
      - bash: env
      - task: DotNetCoreCLI@2
        displayName: build the code
        inputs:
          command: build
          projects: src/NopCommerce.sln
          configuration: Release


  - job: dockerbuild
    displayName: docker image build
    pool: 
      name: Azure Pipelines
      vmImage: ubuntu-22.04    
      dependsOn: dotnetbuild  
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: mydockerhub
            command: 'buildAndPush'
            repository: vsmetgud/nop
            Dockerfile: '**/Dockerfile'
            tags: $(Build.BuildId)