trigger:
  - main
    
pool: default

steps:
  - task: DotNetCoreCLI@2
    displayName: Build&package
    inputs:
      command: 'build'
      projects: src/ NopCommerce.sln
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      publishTestResults: true
      zipAfterPublish: true
      configuration: '$(BuildConfiguration)'
