trigger:
  - master
    
pool: 
  name: Azure Pipelines
  vmImage: ubuntu-22.04

steps:
  - task: DotNetCoreCLI@2
    displayName: Build&package
    inputs:
      command: 'build'
      projects: src/ NopCommerce.sln

