---
pool:
  name: Azure Pipelines  
  vmImage: ubuntu-22.04

trigger:
  - master


steps: 
  - task: DotNetCoreCLI@2
    displayName: build the code
    inputs:
      command: build
      projects: src/NopCommerce.sln
      configuration: Release

  - task: DotNetCoreCLI@2
    displayName: publish the nopcommerce
    inputs:
      command: publish
      projects: src/Presentation/Nop.Web/Nop.Web.csproj
      zipAfterPublish: true
      configuration: Release

  